data = [
    [
        None,
        [[1755159808965002, 99190768, 1311633817], None, None, None, None, [[1]]],
        0,
        "AJ2daIrzOvCPpt8PmeO38QQ",
        "HW39Wt2fipUsAB7HxABG---------tbcfp5AAAAAGidnQAOd6-OA",
    ],
    [
        # airport info
        [
            [
                [
                    ["MYJ", 0],
                    "松山機場",
                    [
                        "/m/0gp6sg",
                        "松山市",
                        [
                            [
                                "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRY6vIP9mDouqw8f5swd-BbuLX3HsPqUZlsM6tpqn3Kd2hEQ5HfAeFjmc0b70q0dGwBcr0hZjUr9ixpcw-Ps1alfjOv06eI-zkNJ7-5Qtg"
                            ],
                            [
                                "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTP4A1NWzIHxsBQ3wsg5tnf8U9DRYNp9jR6jstuJOu9h2G8VHc6n6VNIj3WgZDFgRUZ_TGS6Rxev1H3Vg"
                            ],
                        ],
                    ],
                    [33.8272222, 132.699722],
                    "JP",
                    0,
                    "日本",
                ]
            ],
            [
                [
                    ["TPE", 0],
                    "臺灣桃園國際機場",
                    [
                        "/m/0ftkx",
                        "台北市",
                        [
                            [
                                "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQMST5lzBTm3sd5w5tOO4YZFWdFgSntIVWqaCH97zNh9_Lx42rE-SexpiflhCSwJtBjNpUWo4f_uIhEu4ul5r4B5UgJCxOuDlKIRPgULbo"
                            ],
                            [
                                "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS2MmLbW-HcXlTwmod5sPj7skSX-bye9dnRXjaDxShX4zk8o66Ef213qGriwZt3zahLCL9v7wFHklhKEg"
                            ],
                        ],
                    ],
                    [25.0802778, 121.232222],
                    "TW",
                    0,
                    "台灣",
                ]
            ],
        ]
    ],

    # multi
    [
        [
            [
                [
                    "multi",
                    ["日本航空", "長榮航空"],
                    [
                        [
                            None,
                            None,
                            "J-Air",
                            "MYJ",
                            "松山機場",
                            "大阪國際機場(伊丹機場)",
                            "ITM",
                            None,
                            [9, 45],
                            None,
                            [10, 35],
                            50,
                            [
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                            ],
                            1,
                            "79 公 分",
                            None,
                            1,
                            "Embraer 170",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["JL", "2302", None, "日本航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            80676,
                            0,
                        ],
                        [
                            None,
                            None,
                            None,
                            "KIX",
                            "關西國際機場第二航廈",
                            "臺灣桃園國際機場",
                            "TPE",
                            None,
                            [18],
                            None,
                            [20, 15],
                            195,
                            [
                                None,
                                1,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                                None,
                                3,
                            ],
                            1,
                            "79 公分",
                            None,
                            1,
                            "Boeing 787-10",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["BR", "129", None, "長榮航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            113276,
                            1,
                        ],
                    ],
                    "MYJ",
                    [2025, 12, 22],
                    [9, 45],
                    "TPE",
                    [2025, 12, 22],
                    [20, 15],
                    690,
                    None,
                    None,
                    0,
                    [
                        [
                            445,
                            "ITM",
                            "KIX",
                            [2],
                            "關西國際機場第二航廈",
                            "大阪市",
                            "大阪國際機場(伊丹機場)",
                            "大 阪市",
                        ]
                    ],
                    None,
                    None,
                    None,
                    "sKupif",
                    [
                        [1755159808965002, 99190768, 1311633817],
                        None,
                        None,
                        None,
                        None,
                        [[2]],
                    ],
                    1,
                    None,
                    None,
                    [
                        None,
                        None,
                        3,
                        31,
                        None,
                        1,
                        1,
                        194000,
                        148000,
                        None,
                        223000,
                        1,
                        0,
                        None,
                        None,
                        None,
                        0,
                    ],
                    [1],
                    [
                        ["JL", "日本航空", "https://www.jal.co.jp/en/jalpri/"],
                        [
                            "BR",
                            "長榮航空",
                            "https://www.evaair.com/zh-tw/fly-prepare/special-assistance-and-inquiry/",
                        ],
                    ],
                    None,
                    None,
                    ["Mytrip", "ETRAVELI_Mytrip"],
                ],
                [
                    [None, 9623],
                    "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEgxKTDIzMDJ8QlIxMjkaCgiXSxAAGgNUV0Q4HXDU+gE=",
                ],
                None,
                0,
                [None, None, None, None, 3, None, [None, 0]],
                [1, 0, 0],
                0,
                [],
                '["CAASA1RXRBoDCJdLIuMBCrgBClsKA01ZShIZMjAyNS0xMi0yMlQwOTo0NTowMCswOTowMBoDSVRNIhkyMDI1LTEyLTIyVDEwOjM1OjAwKzA5OjAwKgJKTDIEMjMwMjoCSkxCBDIzMDJIAVIDRTcwClkKA0tJWBIZMjAyNS0xMi0yMlQxODowMDowMCswOTowMBoDVFBFIhkyMDI1LTEyLTIyVDIwOjE1OjAwKzA4OjAwKgJCUjIDMTI5OgJCUkIDMTI5SAFSAzc4MRIECAMQARgBKAAyHAoM5pel5pys6Iiq56m6Cgzplbfmpq7oiKrnqbo\\u003d"]',
                [[2]],
                0,
            ]
        ],
        None,
        0,
        0,
        [1],
    ],

    # index 3
    [
        [
            [
                [
                    "multi",
                    ["日本航空", "國泰航空"],
                    [
                        [
                            None,
                            None,
                            None,
                            "MYJ",
                            "松山機場",
                            "東京國際機場(羽田機場)",
                            "HND",
                            None,
                            [18, 55],
                            None,
                            [20, 15],
                            80,
                            [
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                                None,
                                None,
                                None,
                                None,
                                1,
                                2,
                            ],
                            1,
                            "79 公分",
                            None,
                            1,
                            "Boeing 737",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["JL", "440", None, "日本航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            94503,
                            1,
                        ],
                        
                        [
                            None,
                            None,
                            None,
                            "NRT",
                            "成田國際機場",
                            "臺灣桃園國際機場",
                            "TPE",
                            1,
                            [15, 20],
                            1,
                            [18, 40],
                            260,
                            [None, 1, None, None, None, None, None, None, None, 1],
                            3,
                            "81 公分",
                            None,
                            1,
                            "Airbus A330",
                            None,
                            0,
                            [2025, 12, 23],
                            [2025, 12, 23],
                            ["CX", "451", None, "國泰航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "81 公分",
                            160948,
                            1,
                        ],
                    ],
                    "MYJ",
                    [2025, 12, 22],
                    [18, 55],
                    "TPE",
                    [2025, 12, 23],
                    [18, 40],
                    1485,
                    1,
                    None,
                    0,
                    [
                        [
                            1145,
                            "HND",
                            "NRT",
                            [1, 2],
                            "成田國際機場",
                            "東京都",
                            "東京國際機場(羽田機場)",
                            "東京都",
                        ]
                    ],
                    None,
                    None,
                    None,
                    "ncmlwe",
                    [
                        [1755159808965002, 99190768, 1311633817],
                        None,
                        None,
                        None,
                        None,
                        [[3]],
                    ],
                    1,
                    None,
                    None,
                    [
                        None,
                        None,
                        3,
                        72,
                        None,
                        1,
                        1,
                        255000,
                        148000,
                        None,
                        223000,
                        3,
                        0,
                        None,
                        None,
                        1,
                        0,
                    ],
                    [1],
                    [
                        ["JL", "日本航空", "https://www.jal.co.jp/en/jalpri/"],
                        [
                            "CX",
                            "國泰航空",
                            "https://www.cathaypacific.com/cx/zh_HK/prepare-trip/help-for-passengers.html",
                        ],
                    ],
                    None,
                    None,
                    ["Mytrip", "ETRAVELI_Mytrip"],
                ],
                [
                    [None, 7175],
                    "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEgtKTDQ0MHxDWDQ1MRoKCIc4EAAaA1RXRDgdcPK6AQ==",
                ],
                None,
                1,
                [None, None, None, None, 3, None, [None, 0]],
                [1, 0, 0],
                0,
                [],
                '["CAASA1RXRBoDCIc4IuEBCrYBClkKA01ZShIZMjAyNS0xMi0yMlQxODo1NTowMCswOTowMBoDSE5EIhkyMDI1LTEyLTIyVDIwOjE1OjAwKzA5OjAwKgJKTDIDNDQwOgJKTEIDNDQwSAFSAzczSApZCgNOUlQSGTIwMjUtMTItMjNUMTU6MjA6MDArMDk6MDAaA1RQRSIZMjAyNS0xMi0yM1QxODo0MDowMCswODowMCoCQ1gyAzQ1MToCQ1hCAzQ1MUgBUgMzMzMSBAgDEAEYASgAMhwKDOaXpeacrOiIquepugoM5ZyL5rOw6Iiq56m6"]',
                [[2]],
                0,
            ],
            [
                [
                    "7C",
                    ["濟州航空"],
                    [
                        [
                            None,
                            None,
                            None,
                            "MYJ",
                            "松山機場",
                            "仁川國際機場",
                            "ICN",
                            None,
                            [9, 40],
                            None,
                            [11, 15],
                            95,
                            [],
                            2,
                            "74 公分",
                            None,
                            1,
                            "Boeing 737",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["7C", "1722", None, "濟州航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "74 公分",
                            83224,
                            1,
                        ],
                        [
                            None,
                            None,
                            None,
                            "ICN",
                            "仁川國際機場",
                            "臺灣桃園國際機場",
                            "TPE",
                            1,
                            [10, 40],
                            1,
                            [12, 35],
                            175,
                            [],
                            2,
                            "74 公分",
                            None,
                            1,
                            "Boeing 737",
                            None,
                            0,
                            [2025, 12, 23],
                            [2025, 12, 23],
                            ["7C", "6101", None, "濟州航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "74 公分",
                            139481,
                            1,
                        ],
                    ],
                    "MYJ",
                    [2025, 12, 22],
                    [9, 40],
                    "TPE",
                    [2025, 12, 23],
                    [12, 35],
                    1675,
                    1,
                    None,
                    0,
                    [
                        [
                            1405,
                            "ICN",
                            "ICN",
                            [1],
                            "仁川國際機場",
                            "首爾",
                            "仁川國際機場",
                            "首爾",
                        ]
                    ],
                    None,
                    None,
                    None,
                    "zPMdEd",
                    [
                        [1755159808965002, 99190768, 1311633817],
                        None,
                        None,
                        None,
                        None,
                        [[4]],
                    ],
                    1,
                    None,
                    None,
                    [
                        None,
                        None,
                        3,
                        51,
                        None,
                        1,
                        1,
                        223000,
                        148000,
                        None,
                        223000,
                        2,
                        0,
                        None,
                        None,
                        1,
                        0,
                    ],
                    [1],
                    [
                        [
                            "7C",
                            "濟州航空",
                            "https://www.jejuair.net/zh-tw/linkService/help/main.do",
                        ]
                    ],
                ],
                [
                    [None, 8894],
                    "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEg03QzE3MjJ8N0M2MTAxGgoIvkUQABoDVFdEOB1w1ucB",
                ],
                None,
                0,
                [None, None, None, None, 1, None, [None, 1]],
                [0, 0, 0],
                0,
                [],
                '["CAASA1RXRBoDCL5FItcBCroBClsKA01ZShIZMjAyNS0xMi0yMlQwOTo0MDowMCswOTowMBoDSUNOIhkyMDI1LTEyLTIyVDExOjE1OjAwKzA5OjAwKgI3QzIEMTcyMjoCN0NCBDE3MjJIAVIDNzM4ClsKA0lDThIZMjAyNS0xMi0yM1QxMDo0MDowMCswOTowMBoDVFBFIhkyMDI1LTEyLTIzVDEyOjM1OjAwKzA4OjAwKgI3QzIENjEwMToCN0NCBDYxMDFIAVIDNzM4EgQIAxABGAEoADIOCgzmv5/lt57oiKrnqbo\\u003d"]',
                [[2]],
                0,
            ],
            [
                [
                    "7C",
                    ["濟州航空"],
                    [
                        [
                            None,
                            None,
                            None,
                            "MYJ",
                            "松山機場",
                            "仁川國際機場",
                            "ICN",
                            None,
                            [15, 40],
                            None,
                            [17, 35],
                            115,
                            [],
                            2,
                            "74 公分",
                            None,
                            1,
                            "Boeing 737",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["7C", "1704", None, "濟州航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "74 公分",
                            83224,
                            1,
                        ],
                        [
                            None,
                            None,
                            None,
                            "ICN",
                            "仁川國際機場",
                            "臺灣桃園國際機場",
                            "TPE",
                            1,
                            [10, 40],
                            1,
                            [12, 35],
                            175,
                            [],
                            2,
                            "74 公分",
                            None,
                            1,
                            "Boeing 737",
                            None,
                            0,
                            [2025, 12, 23],
                            [2025, 12, 23],
                            ["7C", "6101", None, "濟州航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "74 公分",
                            139481,
                            1,
                        ],
                    ],
                    "MYJ",
                    [2025, 12, 22],
                    [15, 40],
                    "TPE",
                    [2025, 12, 23],
                    [12, 35],
                    1315,
                    1,
                    None,
                    0,
                    [
                        [
                            1025,
                            "ICN",
                            "ICN",
                            [1],
                            "仁川國際機場",
                            "首爾",
                            "仁川國際機場",
                            "首爾",
                        ]
                    ],
                    None,
                    None,
                    None,
                    "uTmWE",
                    [
                        [1755159808965002, 99190768, 1311633817],
                        None,
                        None,
                        None,
                        None,
                        [[5]],
                    ],
                    1,
                    None,
                    None,
                    [
                        None,
                        None,
                        3,
                        51,
                        None,
                        1,
                        1,
                        223000,
                        148000,
                        None,
                        223000,
                        2,
                        0,
                        None,
                        None,
                        1,
                        0,
                    ],
                    [1],
                    [
                        [
                            "7C",
                            "濟州航空",
                            "https://www.jejuair.net/zh-tw/linkService/help/main.do",
                        ]
                    ],
                ],
                [
                    [None, 9098],
                    "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEg03QzE3MDR8N0M2MTAxGgoIikcQABoDVFdEOB1w/uwB",
                ],
                None,
                0,
                [None, None, None, None, 1, None, [None, 1]],
                [0, 0, 0],
                0,
                [],
                '["CAASA1RXRBoDCIpHItcBCroBClsKA01ZShIZMjAyNS0xMi0yMlQxNTo0MDowMCswOTowMBoDSUNOIhkyMDI1LTEyLTIyVDE3OjM1OjAwKzA5OjAwKgI3QzIEMTcwNDoCN0NCBDE3MDRIAVIDNzM4ClsKA0lDThIZMjAyNS0xMi0yM1QxMDo0MDowMCswOTowMBoDVFBFIhkyMDI1LTEyLTIzVDEyOjM1OjAwKzA4OjAwKgI3QzIENjEwMToCN0NCBDYxMDFIAVIDNzM4EgQIAxABGAEoADIOCgzmv5/lt57oiKrnqbo\\u003d"]',
                [[2]],
                0,
            ],
            [
                [
                    "multi",
                    ["日本航空", "國泰航空"],
                    [
                        [
                            None,
                            None,
                            None,
                            "MYJ",
                            "松山機場",
                            "東京國際機場(羽田機場)",
                            "HND",
                            None,
                            [9, 30],
                            None,
                            [10, 50],
                            80,
                            [
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                                None,
                                None,
                                None,
                                None,
                                1,
                                2,
                            ],
                            1,
                            "79 公分",
                            None,
                            1,
                            "Boeing 737",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["JL", "432", None, "日本航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            94503,
                            1,
                        ],
                        [
                            None,
                            None,
                            None,
                            "NRT",
                            "成田 國際機場",
                            "臺灣桃園國際機場",
                            "TPE",
                            None,
                            [15, 20],
                            None,
                            [18, 40],
                            260,
                            [None, 1, None, None, None, None, None, None, None, 1],
                            3,
                            "81 公分",
                            None,
                            1,
                            "Airbus A330",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["CX", "451", None, "國泰航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "81 公分",
                            160948,
                            1,
                        ],
                    ],
                    "MYJ",
                    [2025, 12, 22],
                    [9, 30],
                    "TPE",
                    [2025, 12, 22],
                    [18, 40],
                    610,
                    None,
                    None,
                    0,
                    [
                        [
                            270,
                            "HND",
                            "NRT",
                            [2],
                            "成田國際機場",
                            "東京都",
                            "東京國際機場(羽田機場)",
                            "東京都",
                        ]
                    ],
                    None,
                    None,
                    None,
                    "Ih9CSb",
                    [
                        [1755159808965002, 99190768, 1311633817],
                        None,
                        None,
                        None,
                        None,
                        [[6]],
                    ],
                    1,
                    None,
                    None,
                    [
                        None,
                        None,
                        3,
                        72,
                        None,
                        1,
                        1,
                        255000,
                        148000,
                        None,
                        223000,
                        3,
                        0,
                        None,
                        None,
                        1,
                        0,
                    ],
                    [1],
                    [
                        ["JL", "日本航空", "https://www.jal.co.jp/en/jalpri/"],
                        [
                            "CX",
                            "國泰航空",
                            "https://www.cathaypacific.com/cx/zh_HK/prepare-trip/help-for-passengers.html",
                        ],
                    ],
                    None,
                    None,
                    ["Gotogate", "ETRAVELI_Gotogate"],
                ],
                [
                    [None, 10853],
                    "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEgtKTDQzMnxDWDQ1MRoKCOVUEAAaA1RXRDgdcNmaAg==",
                ],
                None,
                0,
                [None, None, None, None, 3, None, [None, 0]],
                [1, 0, 0],
                0,
                [],
                '["CAASA1RXRBoDCOVUIuEBCrYBClkKA01ZShIZMjAyNS0xMi0yMlQwOTozMDowMCswOTowMBoDSE5EIhkyMDI1LTEyLTIyVDEwOjUwOjAwKzA5OjAwKgJKTDIDNDMyOgJKTEIDNDMySAFSAzczSApZCgNOUlQSGTIwMjUtMTItMjJUMTU6MjA6MDArMDk6MDAaA1RQRSIZMjAyNS0xMi0yMlQxODo0MDowMCswODowMCoCQ1gyAzQ1MToCQ1hCAzQ1MUgBUgMzMzMSBAgDEAEYASgAMhwKDOaXpeacrOiIquepugoM5ZyL5rOw6Iiq56m6"]',
                [[2]],
                0,
            ],
            [
                [
                    "multi",
                    ["日本航空", "長榮航空"],
                    [
                        [
                            None,
                            None,
                            "J-Air",
                            "MYJ",
                            "松山機場",
                            "福岡國際機場",
                            "FUK",
                            None,
                            [17, 50],
                            None,
                            [18, 45],
                            55,
                            [
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                            ],
                            1,
                            "79 公分",
                            None,
                            1,
                            "Embraer 170",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["JL", "3608", None, "日本航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            66632,
                            0,
                        ],
                        [
                            None,
                            None,
                            None,
                            "FUK",
                            "福岡國際機場",
                            "臺灣桃園國際機場",
                            "TPE",
                            1,
                            [12, 15],
                            1,
                            [13, 50],
                            155,
                            [
                                None,
                                1,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                                None,
                                3,
                            ],
                            1,
                            "79 公分",
                            None,
                            1,
                            "Boeing 787",
                            [None, 1],
                            0,
                            [2025, 12, 23],
                            [2025, 12, 23],
                            ["BR", "105", None, "長榮航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            103710,
                            1,
                        ],
                    ],
                    "MYJ",
                    [2025, 12, 22],
                    [17, 50],
                    "TPE",
                    [2025, 12, 23],
                    [13, 50],
                    1260,
                    1,
                    None,
                    0,
                    [
                        [
                            1050,
                            "FUK",
                            "FUK",
                            [1],
                            "福岡國際機場",
                            "福岡市",
                            "福岡國際機場",
                            "福岡市",
                        ]
                    ],
                    None,
                    None,
                    None,
                    "t5Blqd",
                    [
                        [1755159808965002, 99190768, 1311633817],
                        None,
                        None,
                        None,
                        None,
                        [[7]],
                    ],
                    1,
                    None,
                    None,
                    [
                        None,
                        None,
                        3,
                        15,
                        None,
                        1,
                        1,
                        170000,
                        148000,
                        None,
                        223000,
                        1,
                        0,
                        None,
                        None,
                        None,
                        0,
                    ],
                    [1],
                    [
                        ["JL", "日本航空", "https://www.jal.co.jp/en/jalpri/"],
                        [
                            "BR",
                            "長榮航空",
                            "https://www.evaair.com/zh-tw/fly-prepare/special-assistance-and-inquiry/",
                        ],
                    ],
                    None,
                    None,
                    ["Expedia", "EXPEDIA"],
                ],
                [
                    [None, 13000],
                    "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEgxKTDM2MDh8QlIxMDUaCgjIZRAAGgNUV0Q4HXDP0gI=",
                ],
                None,
                0,
                [None, None, None, None, 3, None, [None, 0]],
                [1, 0, 0],
                0,
                [],
                '["CAASA1RXRBoDCMhlIuMBCrgBClsKA01ZShIZMjAyNS0xMi0yMlQxNzo1MDowMCswOTowMBoDRlVLIhkyMDI1LTEyLTIyVDE4OjQ1OjAwKzA5OjAwKgJKTDIEMzYwODoCSkxCBDM2MDhIAVIDRTcwClkKA0ZVSxIZMjAyNS0xMi0yM1QxMjoxNTowMCswOTowMBoDVFBFIhkyMDI1LTEyLTIzVDEzOjUwOjAwKzA4OjAwKgJCUjIDMTA1OgJCUkIDMTA1SAFSAzc4ORIECAMQARgBKAAyHAoM5pel5pys6Iiq56m6Cgzplbfmpq7oiKrnqbo\\u003d"]',
                [[2]],
                0,
            ],
            [
                [
                    "multi",
                    ["日本航空", "長榮航空"],
                    [
                        [
                            None,
                            None,
                            "J-Air",
                            "MYJ",
                            "松山機場",
                            "福岡國際機場",
                            "FUK",
                            None,
                            [14, 35],
                            None,
                            [15, 25],
                            50,
                            [
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                            ],
                            1,
                            "79 公分",
                            None,
                            1,
                            "Embraer 170",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["JL", "3602", None, "日本航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            66632,
                            0,
                        ],
                        [
                            None,
                            None,
                            None,
                            "FUK",
                            "福岡國際機場",
                            "臺灣桃園國際機場",
                            "TPE",
                            None,
                            [20, 55],
                            None,
                            [22, 35],
                            160,
                            [],
                            1,
                            "79 公分",
                            None,
                            1,
                            "Airbus A321",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["BR", "101", None, "長榮航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            152822,
                            1,
                        ],
                    ],
                    "MYJ",
                    [2025, 12, 22],
                    [14, 35],
                    "TPE",
                    [2025, 12, 22],
                    [22, 35],
                    540,
                    None,
                    None,
                    0,
                    [
                        [
                            330,
                            "FUK",
                            "FUK",
                            None,
                            "福岡國際機場",
                            "福岡市",
                            "福岡國際機場",
                            "福岡市",
                        ]
                    ],
                    None,
                    None,
                    None,
                    "ts3lVe",
                    [
                        [1755159808965002, 99190768, 1311633817],
                        None,
                        None,
                        None,
                        None,
                        [[8]],
                    ],
                    1,
                    None,
                    None,
                    [
                        None,
                        None,
                        3,
                        48,
                        None,
                        1,
                        1,
                        219000,
                        148000,
                        None,
                        223000,
                        2,
                        0,
                        None,
                        None,
                        None,
                        0,
                    ],
                    [1],
                    [
                        ["JL", "日本航空", "https://www.jal.co.jp/en/jalpri/"],
                        [
                            "BR",
                            "長榮航空",
                            "https://www.evaair.com/zh-tw/fly-prepare/special-assistance-and-inquiry/",
                        ],
                    ],
                    None,
                    None,
                    ["Expedia", "EXPEDIA"],
                ],
                [
                    [None, 14437],
                    "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEgxKTDM2MDJ8QlIxMDEaCgjlcBAAGgNUV0Q4HXCH+AI=",
                ],
                None,
                0,
                [None, None, None, None, 3, None, [None, 0]],
                [1, 0, 0],
                0,
                [],
                '["CAASA1RXRBoDCOVwIuMBCrgBClsKA01ZShIZMjAyNS0xMi0yMlQxNDozNTowMCswOTowMBoDRlVLIhkyMDI1LTEyLTIyVDE1OjI1OjAwKzA5OjAwKgJKTDIEMzYwMjoCSkxCBDM2MDJIAVIDRTcwClkKA0ZVSxIZMjAyNS0xMi0yMlQyMDo1NTowMCswOTowMBoDVFBFIhkyMDI1LTEyLTIyVDIyOjM1OjAwKzA4OjAwKgJCUjIDMTAxOgJCUkIDMTAxSAFSAzMyMRIECAMQARgBKAAyHAoM5pel5pys6Iiq56m6Cgzplbfmpq7oiKrnqbo\\u003d"]',
                [[2]],
                0,
            ],
            [
                [
                    "multi",
                    ["日本航空", "星宇航空"],
                    [
                        [
                            None,
                            None,
                            "J-Air",
                            "MYJ",
                            "松山機場",
                            "福岡國際機場",
                            "FUK",
                            None,
                            [14, 35],
                            None,
                            [15, 25],
                            50,
                            [
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                            ],
                            1,
                            "79 公分",
                            None,
                            1,
                            "Embraer 170",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["JL", "3602", None, "日本航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            66632,
                            0,
                        ],
                        [
                            None,
                            None,
                            None,
                            "FUK",
                            "福岡國際機場",
                            "臺灣桃園國際機場",
                            "TPE",
                            None,
                            [19, 10],
                            None,
                            [20, 50],
                            160,
                            [
                                None,
                                1,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                                None,
                                3,
                            ],
                            1,
                            "79 公分",
                            None,
                            1,
                            "Airbus A330-900neo",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["JX", "841", None, "星宇航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            112901,
                            1,
                        ],
                    ],
                    "MYJ",
                    [2025, 12, 22],
                    [14, 35],
                    "TPE",
                    [2025, 12, 22],
                    [20, 50],
                    435,
                    None,
                    None,
                    0,
                    [
                        [
                            225,
                            "FUK",
                            "FUK",
                            None,
                            "福岡國際機場",
                            "福岡市",
                            "福岡國際機場",
                            "福岡市",
                        ]
                    ],
                    None,
                    None,
                    None,
                    "IltdIc",
                    [
                        [1755159808965002, 99190768, 1311633817],
                        None,
                        None,
                        None,
                        None,
                        [[9]],
                    ],
                    1,
                    None,
                    None,
                    [
                        None,
                        None,
                        3,
                        22,
                        None,
                        1,
                        1,
                        180000,
                        148000,
                        None,
                        223000,
                        1,
                        0,
                        None,
                        None,
                        None,
                        0,
                    ],
                    [1],
                    [
                        ["JL", "日本航空", "https://www.jal.co.jp/en/jalpri/"],
                        [
                            "JX",
                            "星宇航空",
                            "https://www.starlux-airlines.com/zh-TW/booking/medical-assistance/wheelchairs-and-mobility-aids",
                        ],
                    ],
                    None,
                    None,
                    ["Gotogate", "ETRAVELI_Gotogate"],
                ],
                [
                    [None, 25987],
                    "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEgxKTDM2MDJ8Slg4NDEaCwiDywEQABoDVFdEOB1w9KQF",
                ],
                None,
                0,
                [None, None, None, None, 3, None, [None, 0]],
                [1, 0, 0],
                0,
                [],
                '["CAASA1RXRBoECIPLASLjAQq4AQpbCgNNWUoSGTIwMjUtMTItMjJUMTQ6MzU6MDArMDk6MDAaA0ZVSyIZMjAyNS0xMi0yMlQxNToyNTowMCswOTowMCoCSkwyBDM2MDI6AkpMQgQzNjAySAFSA0U3MApZCgNGVUsSGTIwMjUtMTItMjJUMTk6MTA6MDArMDk6MDAaA1RQRSIZMjAyNS0xMi0yMlQyMDo1MDowMCswODowMCoCSlgyAzg0MToCSlhCAzg0MUgBUgMzMzkSBAgDEAEYASgAMhwKDOaXpeacrOiIquepugoM5pif5a6H6Iiq56m6"]',
                [[2]],
                0,
            ],
            [
                [
                    "multi",
                    ["日本航空", "中華航空"],
                    [
                        [
                            None,
                            None,
                            None,
                            "MYJ",
                            "松山機場",
                            "東京國際機場(羽田機場)",
                            "HND",
                            None,
                            [17, 35],
                            None,
                            [19],
                            85,
                            [
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                                None,
                                None,
                                None,
                                None,
                                1,
                                2,
                            ],
                            4,
                            None,
                            None,
                            3,
                            "Boeing 737",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["JL", "438", None, "日本航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            None,
                            141754,
                            1,
                        ],
                        [
                            None,
                            None,
                            None,
                            "NRT",
                            "成田國際機場",
                            "臺灣桃園國際機場",
                            "TPE",
                            1,
                            [14, 35],
                            1,
                            [17, 45],
                            250,
                            [
                                None,
                                1,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                                None,
                                2,
                            ],
                            5,
                            None,
                            [["JL", "5047", None, "日本航空"]],
                            3,
                            "Airbus A350",
                            [None, 1],
                            0,
                            [2025, 12, 23],
                            [2025, 12, 23],
                            ["CI", "101", None, "中華航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            None,
                            722552,
                            1,
                        ],
                    ],
                    "MYJ",
                    [2025, 12, 22],
                    [17, 35],
                    "TPE",
                    [2025, 12, 23],
                    [17, 45],
                    1510,
                    1,
                    None,
                    0,
                    [
                        [
                            1175,
                            "HND",
                            "NRT",
                            [1, 2],
                            "成田國際機場",
                            "東京都",
                            "東京國際機場(羽田機場)",
                            "東京都",
                        ]
                    ],
                    None,
                    None,
                    None,
                    "HtArWe",
                    [
                        [1755159808965002, 99190768, 1311633817],
                        None,
                        None,
                        None,
                        None,
                        [[10]],
                    ],
                    1,
                    None,
                    None,
                    [
                        None,
                        None,
                        3,
                        484,
                        None,
                        1,
                        1,
                        864000,
                        148000,
                        None,
                        223000,
                        3,
                        0,
                        None,
                        None,
                        1,
                        0,
                    ],
                    [1],
                    [
                        ["JL", "日本航空", "https://www.jal.co.jp/en/jalpri/"],
                        [
                            "CI",
                            "中華航空",
                            "https://www.china-airlines.com/tw/zh/fly/prepare-for-the-fly/special-assistance/index",
                        ],
                    ],
                    None,
                    None,
                    ["Mytrip", "ETRAVELI_Mytrip"],
                ],
                [
                    [None, 29860],
                    "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEgtKTDQzOHxDSTEwMRoLCKTpARAAGgNUV0Q4HXDliQY=",
                ],
                None,
                0,
                [None, None, None, None, 1, None, [None, 1]],
                [0, 0, 0],
                0,
                [],
                '["CAASA1RXRBoECKTpASLUAQq3AQpZCgNNWUoSGTIwMjUtMTItMjJUMTc6MzU6MDArMDk6MDAaA0hORCIZMjAyNS0xMi0yMlQxOTowMDowMCswOTowMCoCSkwyAzQzODoCSkxCAzQzOEgDUgM3M0gKWgoDTlJUEhkyMDI1LTEyLTIzVDE0OjM1OjAwKzA5OjAwGgNUUEUiGTIwMjUtMTItMjNUMTc6NDU6MDArMDg6MDAqAkNJMgMxMDE6AkpMQgQ1MDQ3SANSAzM1ORIECAMQARgBKAAyDgoM5pel5pys6Iiq56m6"]',
                [[2]],
                0,
            ],
            [
                [
                    "multi",
                    ["日本航空", "中華航空"],
                    [
                        [
                            None,
                            None,
                            "J-Air",
                            "MYJ",
                            "松山機場",
                            "大阪國際機場(伊丹機場)",
                            "ITM",
                            None,
                            [9, 45],
                            None,
                            [10, 35],
                            50,
                            [
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                            ],
                            1,
                            "79 公分",
                            None,
                            1,
                            "Embraer 170",
                            None,
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["JL", "2302", None, "日本航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            80676,
                            0,
                        ],
                        [
                            None,
                            None,
                            None,
                            "KIX",
                            "關西國際機場第二航廈",
                            "臺灣桃園國際機場",
                            "TPE",
                            None,
                            [14, 30],
                            None,
                            [16, 45],
                            195,
                            [
                                None,
                                None,
                                None,
                                None,
                                None,
                                1,
                                None,
                                None,
                                None,
                                1,
                                None,
                                3,
                            ],
                            1,
                            "79 公分",
                            [["JL", "5105", None, "日本航空"]],
                            1,
                            "Airbus A321neo",
                            [None, 1],
                            0,
                            [2025, 12, 22],
                            [2025, 12, 22],
                            ["CI", "153", None, "中華航空"],
                            None,
                            None,
                            1,
                            None,
                            None,
                            None,
                            None,
                            "79 公分",
                            159986,
                            1,
                        ],
                    ],
                    "MYJ",
                    [2025, 12, 22],
                    [9, 45],
                    "TPE",
                    [2025, 12, 22],
                    [16, 45],
                    480,
                    None,
                    None,
                    0,
                    [
                        [
                            235,
                            "ITM",
                            "KIX",
                            [2],
                            "關西國際機場第二航廈",
                            "大阪市",
                            "大阪國際機場(伊丹機場)",
                            "大阪市",
                        ]
                    ],
                    None,
                    None,
                    None,
                    "C8Iqi",
                    [
                        [1755159808965002, 99190768, 1311633817],
                        None,
                        None,
                        None,
                        None,
                        [[11]],
                    ],
                    1,
                    None,
                    None,
                    [
                        None,
                        None,
                        3,
                        63,
                        None,
                        1,
                        1,
                        241000,
                        148000,
                        None,
                        223000,
                        3,
                        0,
                        None,
                        None,
                        None,
                        0,
                    ],
                    [1],
                    [
                        ["JL", "日本航空", "https://www.jal.co.jp/en/jalpri/"],
                        [
                            "CI",
                            "中華航空",
                            "https://www.china-airlines.com/tw/zh/fly/prepare-for-the-fly/special-assistance/index",
                        ],
                    ],
                    None,
                    None,
                    ["Mytrip", "ETRAVELI_Mytrip"],
                ],
                [
                    [None, 35563],
                    "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEgxKTDIzMDJ8Q0kxNTMaCwjrlQIQABoDVFdEOB1wq54H",
                ],
                None,
                0,
                [None, None, None, None, 1, None, [None, 1]],
                [0, 0, 0],
                0,
                [],
                '["CAASA1RXRBoECOuVAiLWAQq5AQpbCgNNWUoSGTIwMjUtMTItMjJUMDk6NDU6MDArMDk6MDAaA0lUTSIZMjAyNS0xMi0yMlQxMDozNTowMCswOTowMCoCSkwyBDIzMDI6AkpMQgQyMzAySAFSA0U3MApaCgNLSVgSGTIwMjUtMTItMjJUMTQ6MzA6MDArMDk6MDAaA1RQRSIZMjAyNS0xMi0yMlQxNjo0NTowMCswODowMCoCQ0kyAzE1MzoCSkxCBDUxMDVIAVIDMzJREgQIAxABGAEoADIOCgzml6XmnKzoiKrnqbo\\u003d"]',
                [[2]],
                0,
            ],
        ],
        45,
        0,
        0,
        [1],
    ],
    None,
    None,
    None,

    # index: 7
    [
        # 7:0
        [[None, 7175], [None, 84057]],

        # 7:1
        [
            [
                ["ONEWORLD", "Oneworld"],
                ["SKYTEAM", "SkyTeam"],
                ["STAR_ALLIANCE", "Star Alliance"],
            ],
            [
                ["MU", "中國東方航空"],
                ["CI", "中華航空"],
                ["JL", "日本航空"],
                ["NH", "全日空航空"],
                ["BR", "長榮航空"],
                ["JX", "星宇航空"],
                ["HA", "夏威夷航空"],
                ["BX", "釜山航空"],
                ["CX", "國泰航空"],
                ["GK", "捷星日本航空"],
                ["7C", "濟州航空"],
                ["OZ", "韓亞航空"],
            ],
        ],

        # 7:2
        [
            [
                ["ITM", "大阪市"],
                ["KIX", "大阪市"],
                ["OKA", "沖繩市"],
                ["NRT", "東京都"],
                ["HND", "東京都"],
                ["ICN", "首爾"],
                ["FUK", "福岡市"],
            ],
            60,
            1410,
        ],
        [435, 1750],
        [[1, 2, 3]],
        [1, 0, 0, 0],
        None,
        [0],
    ],

    None,
    None,
    None,

    # index: 11
    [
        [
            "CI",
            "中華航空",
            "https://www.china-airlines.com/us/en/fly/prepare-for-the-fly/baggage/baggage-rules",
        ],
        ["JL", "日本航空", "https://www.jal.co.jp/jp/en/inter/baggage/"],
        ["BR", "長榮航空", "https://www.evaair.com/zh-tw/fly-prepare/baggage/"],
        [
            "JX",
            "星宇航空",
            "https://www.starlux-airlines.com/en-TW/check-in-fly/baggage-information/general",
        ],
        [
            "CX",
            "國泰航空",
            "https://www.cathaypacific.com/cx/zh_TW/baggage.html?cxsource=TOP-NAV_MANAGE_3_1",
        ],
        [
            "7C",
            "濟州航空",
            "https://www.jejuair.net/en/linkService/boardingProcessGuide/trustBaggage.do",
        ],
    ],

    # index 12
    [
        "EAEaBAgDEAEhAAAAAAAHvEAqA1RXRDIYChYKA01ZShIDVFBFGgoyMDI1LTEyLTIyUAFiLQoeCgcKA01ZShABEgcKA1RQRRABGgoyMDI1LTEyLTIyGgsKBAgDEAEQAYgBAWgAcNG2rTJwyo3zLnCF0asycKGz4y5w+Y3zLg==",
        0,
    ],

    None,
    [[1755159808965002, 99190768, 1311633817], None, None, None, None, [[0]]],
    None,
    None,

    # index 17
    [
        [
            ["FUK", 0],
            "福岡國際機場",
            [
                "/m/0gqkd",
                "福岡市",
                [
                    [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdtwYNURENNIrY9sz1rL9yS9C8pRqt2be6ZsDfIGBYD9y5byAx2dcUC978hQWx4x13VE_ZDjXcYzk_dbL9Q1ZaM4dSO4IbLn85it5LBSc"
                    ],
                    [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlhohFOU0GrWknGYzzby90BdqYGLjnkC4vc_pl-imo3QZk25MTrFsCXuT65snMN7V1naHic1N8fzS09Q"
                    ],
                ],
            ],
            [33.5858333, 130.449444],
            "JP",
            0,
            "日本",
        ],
        [
            ["/m/0gqkd", 4],
            "福岡市",
            [
                "/m/0gqkd",
                "福岡市",
                [
                    [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdtwYNURENNIrY9sz1rL9yS9C8pRqt2be6ZsDfIGBYD9y5byAx2dcUC978hQWx4x13VE_ZDjXcYzk_dbL9Q1ZaM4dSO4IbLn85it5LBSc"
                    ],
                    [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlhohFOU0GrWknGYzzby90BdqYGLjnkC4vc_pl-imo3QZk25MTrFsCXuT65snMN7V1naHic1N8fzS09Q"
                    ],
                ],
                "櫛田神社、舞鶴公園和海灘",
                "以櫛田神社等古寺廟、海灘和舞鶴公園而聞名的九州島城市。",
                "FUK",
            ],
            [33.5901838, 130.4016888],
            "JP",
            None,
            "日本",
        ],
        [
            ["HND", 0],
            "東京國際機場(羽田機場)",
            [
                "/m/07dfk",
                "東京都",
                [
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRLnIToEgwiM_jV3cbw5eQZoUAIg6XqdrJAiClDyyg0w-JBSRN5ZeOT-iFb3SvwkwP1uoBCmT-gKE5VcyCYf-xq4guL4NAFICSaNyOnYOA"
                    ],
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTqHkzEeI2bSglPzmSGZL7bxXmn0wJgOn2ZtEN8I47uBnzY1CnHzGtD-YseJXqyexcAcw_uJp-D5HTkCg"
                    ],
                ],
            ],
            [35.5533333, 139.781111],
            "JP",
            0,
            "日本",
        ],
        [
            ["/m/07dfk", 4],
            "東京都",
            [
                "/m/07dfk",
                "東京都",
                [
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRLnIToEgwiM_jV3cbw5eQZoUAIg6XqdrJAiClDyyg0w-JBSRN5ZeOT-iFb3SvwkwP1uoBCmT-gKE5VcyCYf-xq4guL4NAFICSaNyOnYOA"
                    ],
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTqHkzEeI2bSglPzmSGZL7bxXmn0wJgOn2ZtEN8I47uBnzY1CnHzGtD-YseJXqyexcAcw_uJp-D5HTkCg"
                    ],
                ],
                "明治神宮、皇居和博物館",
                "摩天大樓、博物館、皇居和明治神宮所在的日本首都。",
                "TYO",
            ],
            [35.6764225, 139.650027],
            "JP",
            None,
            "日本",
        ],
        [
            ["ICN", 0],
            "仁川國際機場",
            [
                "/m/0hsqf",
                "首爾",
                [
                    [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxR7y_Va8i68eRlNWn4Omq2FHwgniQAe29Wb-NPNbNQCBFLvSQpBXOtZw5ZcbOagsrS83GufEhdkmk7mppoRZWU9enYxup7h1WZdBl7v4"
                    ],
                    [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaeVwigGtqKE3WHRHlXdsogk_5ZpMVDw4LeWvbjUbezo_88sViW8V2x7FhQlWlIeoYrrNajK9btPW_8w"
                    ],
                ],
            ],
            [37.4625, 126.439167],
            "KR",
            0,
            "南韓",
        ],
        [
            ["/m/0hsqf", 4],
            "首爾",
            [
                "/m/0hsqf",
                "首爾",
                [
                    [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxR7y_Va8i68eRlNWn4Omq2FHwgniQAe29Wb-NPNbNQCBFLvSQpBXOtZw5ZcbOagsrS83GufEhdkmk7mppoRZWU9enYxup7h1WZdBl7v4"
                    ],
                    [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaeVwigGtqKE3WHRHlXdsogk_5ZpMVDw4LeWvbjUbezo_88sViW8V2x7FhQlWlIeoYrrNajK9btPW_8w"
                    ],
                ],
                "景福宮和首爾塔",
                "南韓的首都。景點包含現代摩天大樓、古廟、景福宮和首爾塔。",
                "SEL",
            ],
            [37.550263, 126.9970831],
            "KR",
            None,
            "南韓",
        ],
        [
            ["ITM", 0],
            "大阪國際機場(伊丹機場)",
            [
                "/m/0dqyw",
                "大阪市",
                [
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR3jKI7Lkj9P49olywFLeY1N_JCP0sLdkXx44vXuyBdWWF2Qu4FCz3dwTl_18a5QGqoRE0_hIHdKSQfmwxATIxo97rwtP0bi082GpSANwM"
                    ],
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSTrQEGi0u09QEhaXC7jvOA-72dXN569lL-E39eTh1dLlQH-HPBVXJvLJ1GSX2x3oZ4R64EfT66yJkmlA"
                    ],
                ],
            ],
            [34.7844444, 135.439167],
            "JP",
            0,
            "日本",
        ],
        [
            ["/m/0dqyw", 4],
            "大阪市",
            [
                "/m/0dqyw",
                "大阪市",
                [
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR3jKI7Lkj9P49olywFLeY1N_JCP0sLdkXx44vXuyBdWWF2Qu4FCz3dwTl_18a5QGqoRE0_hIHdKSQfmwxATIxo97rwtP0bi082GpSANwM"
                    ],
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSTrQEGi0u09QEhaXC7jvOA-72dXN569lL-E39eTh1dLlQH-HPBVXJvLJ1GSX2x3oZ4R64EfT66yJkmlA"
                    ],
                ],
                "以大阪城聞名的現代港都",
                "位於日本的現代港都。以繁忙的 夜生活、餐廳和大阪城聞名。",
                "OSA",
            ],
            [34.6937249, 135.5022535],
            "JP",
            None,
            "日本",
        ],
        [
            ["KIX", 0],
            "關西國際機場第二航廈",
            [
                "/m/0dqyw",
                "大阪市",
                [
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR3jKI7Lkj9P49olywFLeY1N_JCP0sLdkXx44vXuyBdWWF2Qu4FCz3dwTl_18a5QGqoRE0_hIHdKSQfmwxATIxo97rwtP0bi082GpSANwM"
                    ],
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSTrQEGi0u09QEhaXC7jvOA-72dXN569lL-E39eTh1dLlQH-HPBVXJvLJ1GSX2x3oZ4R64EfT66yJkmlA"
                    ],
                ],
            ],
            [34.4341667, 135.232778],
            "JP",
            0,
            "日本",
        ],
        [
            ["MYJ", 0],
            "松山機場",
            [
                "/m/0gp6sg",
                "松山市",
                [
                    [
                        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRY6vIP9mDouqw8f5swd-BbuLX3HsPqUZlsM6tpqn3Kd2hEQ5HfAeFjmc0b70q0dGwBcr0hZjUr9ixpcw-Ps1alfjOv06eI-zkNJ7-5Qtg"
                    ],
                    [
                        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTP4A1NWzIHxsBQ3wsg5tnf8U9DRYNp9jR6jstuJOu9h2G8VHc6n6VNIj3WgZDFgRUZ_TGS6Rxev1H3Vg"
                    ],
                ],
            ],
            [33.8272222, 132.699722],
            "JP",
            0,
            "日本",
        ],
        [
            ["/m/0gp6sg", 4],
            "松山市",
            [
                "/m/0gp6sg",
                "松山市",
                [
                    [
                        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRY6vIP9mDouqw8f5swd-BbuLX3HsPqUZlsM6tpqn3Kd2hEQ5HfAeFjmc0b70q0dGwBcr0hZjUr9ixpcw-Ps1alfjOv06eI-zkNJ7-5Qtg"
                    ],
                    [
                        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTP4A1NWzIHxsBQ3wsg5tnf8U9DRYNp9jR6jstuJOu9h2G8VHc6n6VNIj3WgZDFgRUZ_TGS6Rxev1H3Vg"
                    ],
                ],
                "道後温泉本館的溫泉和封建時代的城堡",
                "位於日本的城市。以道後温泉本館的溫泉、佛寺和松山城聞名。",
                "MYJ",
            ],
            [33.8355117, 132.7639923],
            "JP",
            None,
            "日本",
        ],
        [
            ["NRT", 0],
            "成田國際機場",
            [
                "/m/07dfk",
                "東京都",
                [
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRLnIToEgwiM_jV3cbw5eQZoUAIg6XqdrJAiClDyyg0w-JBSRN5ZeOT-iFb3SvwkwP1uoBCmT-gKE5VcyCYf-xq4guL4NAFICSaNyOnYOA"
                    ],
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTqHkzEeI2bSglPzmSGZL7bxXmn0wJgOn2ZtEN8I47uBnzY1CnHzGtD-YseJXqyexcAcw_uJp-D5HTkCg"
                    ],
                ],
            ],
            [35.7652778, 140.385556],
            "JP",
            0,
            "日本",
        ],
        [
            ["OKA", 0],
            "那霸機場",
            [
                "/m/0gp71x",
                "沖繩市",
                [
                    [
                        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQtjoi0G69dJ_GqaXRrfM-FA1lh7Zn4Jn96NCjfUOfVRpM0w0cXMNOi4dxOX2CpVFc26msxOJwvCurgWKT2afU9bTEiYyAa-x3WXZ0XVzM"
                    ],
                    [
                        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS3EY8oobyd3h_d0kH_h6csFIX_MMmk3VA-AKiM70LtnUE01JYQOVfirxCnnof10Jz4njxF1m8Z8uoFoQ"
                    ],
                ],
            ],
            [26.1958333, 127.645833],
            "JP",
            0,
            "日本",
        ],
        [
            ["/m/0gp71x", 4],
            "沖繩市",
            [
                "/m/0gp71x",
                "沖繩市",
                [
                    [
                        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQtjoi0G69dJ_GqaXRrfM-FA1lh7Zn4Jn96NCjfUOfVRpM0w0cXMNOi4dxOX2CpVFc26msxOJwvCurgWKT2afU9bTEiYyAa-x3WXZ0XVzM"
                    ],
                    [
                        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS3EY8oobyd3h_d0kH_h6csFIX_MMmk3VA-AKiM70LtnUE01JYQOVfirxCnnof10Jz4njxF1m8Z8uoFoQ"
                    ],
                ],
                "動物園、公園、肉 排和音樂會",
                None,
                "OKA",
            ],
            [26.3343533, 127.8056058],
            "JP",
            None,
            "日本",
        ],
        [
            ["OSA", 0],
            "Metropolitan Area",
            [
                "/m/0dqyw",
                "大阪市",
                [
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR3jKI7Lkj9P49olywFLeY1N_JCP0sLdkXx44vXuyBdWWF2Qu4FCz3dwTl_18a5QGqoRE0_hIHdKSQfmwxATIxo97rwtP0bi082GpSANwM"
                    ],
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSTrQEGi0u09QEhaXC7jvOA-72dXN569lL-E39eTh1dLlQH-HPBVXJvLJ1GSX2x3oZ4R64EfT66yJkmlA"
                    ],
                ],
            ],
            [34.6937378, 135.50216510000004],
            "JP",
            0,
            "日本",
        ],
        [
            ["SEL", 0],
            "Metropolitan Area",
            [
                "/m/0hsqf",
                "首爾",
                [
                    [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxR7y_Va8i68eRlNWn4Omq2FHwgniQAe29Wb-NPNbNQCBFLvSQpBXOtZw5ZcbOagsrS83GufEhdkmk7mppoRZWU9enYxup7h1WZdBl7v4"
                    ],
                    [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaeVwigGtqKE3WHRHlXdsogk_5ZpMVDw4LeWvbjUbezo_88sViW8V2x7FhQlWlIeoYrrNajK9btPW_8w"
                    ],
                ],
            ],
            [37.566535, 126.97796919999999],
            "KR",
            0,
            "南韓",
        ],
        [
            ["TPE", 0],
            "臺灣桃園國際機場",
            [
                "/m/0ftkx",
                "台北市",
                [
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQMST5lzBTm3sd5w5tOO4YZFWdFgSntIVWqaCH97zNh9_Lx42rE-SexpiflhCSwJtBjNpUWo4f_uIhEu4ul5r4B5UgJCxOuDlKIRPgULbo"
                    ],
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS2MmLbW-HcXlTwmod5sPj7skSX-bye9dnRXjaDxShX4zk8o66Ef213qGriwZt3zahLCL9v7wFHklhKEg"
                    ],
                ],
            ],
            [25.0802778, 121.232222],
            "TW",
            0,
            "台灣",
        ],
        [
            ["/m/0ftkx", 4],
            "台北市",
            [
                "/m/0ftkx",
                "台北市",
                [
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQMST5lzBTm3sd5w5tOO4YZFWdFgSntIVWqaCH97zNh9_Lx42rE-SexpiflhCSwJtBjNpUWo4f_uIhEu4ul5r4B5UgJCxOuDlKIRPgULbo"
                    ],
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS2MmLbW-HcXlTwmod5sPj7skSX-bye9dnRXjaDxShX4zk8o66Ef213qGriwZt3zahLCL9v7wFHklhKEg"
                    ],
                ],
                "兼具活力與現代感的台灣首都",
                "充滿現代氛圍的台灣首都。景 點包含知名夜市和國立故宮博物院。",
                "TPE",
            ],
            [25.0329636, 121.5654268],
            "TW",
            None,
            "台灣",
        ],
        [
            ["TYO", 0],
            "Metropolitan Area",
            [
                "/m/07dfk",
                "東京都",
                [
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRLnIToEgwiM_jV3cbw5eQZoUAIg6XqdrJAiClDyyg0w-JBSRN5ZeOT-iFb3SvwkwP1uoBCmT-gKE5VcyCYf-xq4guL4NAFICSaNyOnYOA"
                    ],
                    [
                        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTqHkzEeI2bSglPzmSGZL7bxXmn0wJgOn2ZtEN8I47uBnzY1CnHzGtD-YseJXqyexcAcw_uJp-D5HTkCg"
                    ],
                ],
            ],
            [35.7090259, 139.7319925],
            "JP",
            0,
            "日本",
        ],
    ],
    None,
    None,
    0,
    None,
    None,
    1,
    None,
    [[None, 7175]],

    # index 26
    [
        [
            "CI",
            "中華航空",
            "https://www.china-airlines.com/tw/zh/fly/prepare-for-the-fly/special-assistance/index",
        ],
        ["JL", "日本航空", "https://www.jal.co.jp/en/jalpri/"],
        [
            "BR",
            "長榮航空",
            "https://www.evaair.com/zh-tw/fly-prepare/special-assistance-and-inquiry/",
        ],
        [
            "JX",
            "星宇航空",
            "https://www.starlux-airlines.com/zh-TW/booking/medical-assistance/wheelchairs-and-mobility-aids",
        ],
        [
            "CX",
            "國泰航空",
            "https://www.cathaypacific.com/cx/zh_HK/prepare-trip/help-for-passengers.html",
        ],
        ["7C", "濟州航空", "https://www.jejuair.net/zh-tw/linkService/help/main.do"],
    ],

    None,
    None,
    None,
    [
        [None, 5574],
        "CjRIVzM5V3QyZmlwVXNBQjdIeEFCRy0tLS0tLS0tLXRiY2ZwNUFBQUFBR2lkblFBT2Q2LU9BEhZjb21wcmVoZW5zaXZlbmVzc19sdXJlGgoIxisQABoDVFdEOB1wmJEB",
    ],
]

for item in data:
    print(item)
